name: cupertino_calendar_picker
description: The cupertino calendar picker package.
version: 1.0.0
repository: https://github.com/philip-soft/cupertino_calendar_picker

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.2
  flutter_test:
    sdk: flutter
