name: cupertino_calendar_picker
description: This package includes a suite of Cupertino-style components that make date and time selection seamless and visually consistent with iOS design principles.
version: 2.0.0
repository: https://github.com/philip-soft/cupertino_calendar_picker

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

screenshots:
  - description: "The cupertino calendar picker in light theme."
    path: doc/calendar_light.png
  - description: "The cupertino calendar picker in dark theme."
    path: doc/calendar_dark.png
