name: cupertino_calendar_picker
description: The package contains an iOS-style calendar picker with the
  capability to display it around your widget.
version: 1.1.2
repository: https://github.com/philip-soft/cupertino_calendar_picker

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  cupertino_icons: ^1.0.8
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter

screenshots:
  - description: "Cupertino calendar picker in light theme."
    path: doc/calendar_light.png
  - description: "Cupertino calendar picker in dark theme."
    path: doc/calendar_dark.png
